apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  ports:
  - name: 9001-9000
    nodePort: 9001
    port: 9001
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
  type: NodePort
status:
  loadBalancer: {}
