apiVersion: apps/v1
kind: Deployment
metadata:
  name: senaite-postgres
  labels:
    app: senaite-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: senaite-postgres
  template:
    metadata:
      labels:
        app: senaite-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: senaite
            - name: POSTGRES_USER
              value: senaiteuser
            - name: POSTGRES_PASSWORD
              value: senaitepass
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /var/lib/senaite-postgres
            type: DirectoryOrCreate

      # volumes:
      #   - name: senaite-db-storage
      #     persistentVolumeClaim:
      #       claimName: senaite-db-pvc
