apiVersion: apps/v1
kind: Deployment
metadata:
  name: senaite-postgres
  labels:
    app: senaite-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: senaite-postgres
  template:
    metadata:
      labels:
        app: senaite-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: senaite
            - name: POSTGRES_USER
              value: senaiteuser
            - name: POSTGRES_PASSWORD
              value: senaitepass
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: senaite-data-pvc
